version: '3.9'

services:
  node-frontend:
    image: frontend_test:latest
    ports:
      - 80:3000
    deploy:
      mode: global

  node-backend:
    image: backend_test:latest
    ports:
      - 3000:3000
    volumes:
      - /vagrant/backend:/var/temp/backend
    deploy:
      mode: global

  mysql-test:
    image: mysql:8.0
    volumes:
      - /var/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      mode: global
